name: Nightly Builds

on:
  push:
    branches:
      - custom
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags --force

      - name: Restore cached files
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.npm
            ./.cache
            ./buildtools/node_modules
          key: ${{ runner.os }}-bunny-${{ hashFiles('**/.cache', '**/package-lock.json', '**/manifest.json') }}
          restore-keys: ${{ runner.os }}-bunny-

      - name: "Setup NodeJS v13"
        uses: actions/setup-node@v2
        with:
          node-version: "13"
          check-latest: true

      - name: "Download NPM packages"
        working-directory: ./buildtools
        run: npm ci

      - name: "Build everything and prune cache"
        working-directory: ./buildtools
        run: npx gulp buildAllAndPrune

      ##
      ## Upload artifacts.
      ##
      - name: "Make artifact names"
        id: artifactNames
        working-directory: ./buildtools
        run: npx gulp makeArtifactNames

      - name: "Upload client artifact"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifactNames.outputs.client }}
          path: |
            build/client/**/*

      - name: "Upload server artifact"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifactNames.outputs.server }}
          path: |
            build/server/**/*

      - name: "Upload lang artifact"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifactNames.outputs.lang }}
          path: |
            build/lang/**/*

      - name: "Upload changelog artifact"
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: |
            build/shared/CHANGELOG.md
